### ISSUE TITLE
any support for amzn linux?

### ISSUE THREAD

**Issue by redbarron23** [sunggun-yu/chef-mongodb3#10]
problem is mongodb repo file is different
https://docs.mongodb.org/manual/tutorial/install-mongodb-on-amazon/

**Comment by sunggun-yu** [comment]
Thank you so much for letting me know this. I'll add the feature for amazon linux.

**Comment by sunggun-yu** [comment]
Thank you for the feature request. Supporting Amazon linux has released. 
Please let me know if it is not working.
