### ISSUE TITLE
Issue with updates on U14.04

### ISSUE THREAD

**Issue by daugustus** [sunggun-yu/chef-mongodb3#13]
Chef runs fail due to the conffile prompt. I can create an override in /etc/apt/apt.conf.d/local- like what is mentioned here ( https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/ ) -but that seems overkill and potentially troublesome. The Cookbook defaults to 3.0.4 currently but 3.0.7 is the latest as of today. It seems that the Cookbook's apt-get command has the correct parameters:
"apt-get -q -y install mongodb-org-shell=3.0.7"

Any ideas on how to handle this? 

Thanks for a great Cookbook!

**Comment by sunggun-yu** [comment]
@daugustus 
Hi, Thank you for raising the issue. 
I'll check as soon as possible. so sorry for the inconvenience.

**Comment by sunggun-yu** [comment]
@daugustus 
HI, 
just quick respond after doing some kitchen testing.
there was no problem in my kitchen testing with U14.04.
can you give me more detail about your environment?
- chef-client version
- dependencies on your wrapper cookbook.

also, it may related to the order of run_list. please try to set apt before the mongodb3 in run_list.

```
"run_list":[
   "recipe[apt]",
   "recipe[mongodb3]"
 ]
```

**Comment by daugustus** [comment]
Chef version 12.4.3
wrapper dependencies:
depends 'database', '~> 4.0.6'
depends 'magic', '~> 1.1.10'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'percona', '~> 0.16.0'
depends 'mongodb3'

and apt is listed in the run list BEFORE our wrapper cookbook

**Comment by daugustus** [comment]
seem to work now- unsure what changed on my end - thanks!
