### ISSUE TITLE
Hardcoded to an unavailable deb version; apt dist should be attribute or computed

### ISSUE THREAD

**Issue by donaldguy** [sunggun-yu/chef-mongodb3#19]
https://github.com/sunggun-yu/chef-mongodb3/blob/20ce6c676dc7a10aced125264a4de4a2c7608f08/recipes/package_repo.rb#L34 hardcodes distribution to '/stable' which has moved on to the '3.2' 

A resource override like this works around:

``` ruby
include_recipe 'mongodb3'
resources('apt_repository[mongodb]').distribution("#{node['lsb']['codename']}/mongodb-org/3.0")
```

but it would be better for the dist to just be computer on minor version number (see directory listing at http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/ ), or at least explicitly an attribute of this cookbook

**Comment by sunggun-yu** [comment]
please check latest release v.4.0.0

**Comment by sunggun-yu** [comment]
I'm closing it out since it is resolved in latest release.
Thank you!
