### ISSUE TITLE
What's the right way to set MongoDB version to 3.0.7

### ISSUE THREAD

**Issue by dblock** [sunggun-yu/chef-mongodb3#23]
I tried this in an attributes file where we set other things and it had no effect.

```
set[:mongodb3][:version] = '3.0.7'
```

**Comment by sunggun-yu** [comment]
could you please try with this in your wrapper?

```
node.set['mongodb3']['version'] = '3.0.7'
```

**Comment by dblock** [comment]
It's the same thing, `node` is implied and `:mongodb3` is equivalent to `['mongodb3']`, these are Mashes. We set a bunch of other stuff, which all works.

**Comment by shortdudey123** [comment]
@dblock try this:
`node.override[:mongodb3][:version] = '3.0.7'`

set is an alias for normal attributes.  I have discovered that sometimes you have to go up to `override` even though `normal` should take precedence over `default`.

**Comment by shortdudey123** [comment]
you should use `3.0.8` anyway unless you have to have `3.0.7`
see http://blog.mongodb.org/post/135337099353/mongodb-308-is-released

**Comment by sunggun-yu** [comment]
@dblock 
Hi, here is temporary solution for installing 3.0.x 
https://github.com/sunggun-yu/chef-mongodb3/blob/6a55907ef96cdf6003316aa0cab272180d38adbd/test/cookbooks/mongodb3-test/recipes/default-30x.rb

there are bunch of attribute setter in default attribute file. and it is bothering installing 3.0.x. I think, I need to move those attribute into recipe to support installing 3.0.x

**Comment by dblock** [comment]
Thanks! Looking forward to a fix so we can just declare it in one place.

**Comment by sunggun-yu** [comment]
@dblock I would recommend to use role instead of wrapper. setting up version working perfectly.
here is some example of mine.

```
{
  "name": "mongodb_rs_0",
  "description": "Role for MongoDB Replica set rs-0",
  "json_class": "Chef::Role",
  "default_attributes": {
    "mongodb3" : {
      "version" : "3.0.6",
      "config" : {
        "mongod" : {
          "storage" : {
            "dbPath" : "/var/lib/mongodb/rs-0",
            "engine" : "wiredTiger",
            "wiredTiger" : {
              "engineConfig" : {
                "cacheSizeGB" : 15,
                "statisticsLogDelaySecs" : 60,
                "journalCompressor" : "snappy",
                "directoryForIndexes" : false
              },
              "collectionConfig" : {
                "blockCompressor" : "snappy"
              },
              "indexConfig" : {
                "prefixCompression" : true
              }
            }
          },
          "replication" : {
            "replSetName" : "rs-0"
          }
        }
      }
    }
  },
  "override_attributes": {
  },
  "chef_type": "role",
  "run_list": [
    "recipe[mongodb3::default]"
  ],
  "env_run_lists": {
  }
}
```
