### ISSUE TITLE
Default to MongoDB 3.2.1

### ISSUE THREAD

**Issue by dblock** [sunggun-yu/chef-mongodb3#24]
3.2.0 -> 3.2.1

As simple as a search/replace? Happy to make a PR.

**Comment by sunggun-yu** [comment]
In actually,
I've tried 3.2.1 before I release 4.0.0. but it was failed to install. :-(
will keep try. thank you.

**Comment by sunggun-yu** [comment]
I could install 3.2.1 today. I'll change the default version as 3.2.1 soon.
Thank you.

```
default['mongodb3']['version'] = '3.2.1'
```
