### ISSUE TITLE
log directory not created in recipes/default.rb

### ISSUE THREAD

**Issue by tuky** [sunggun-yu/chef-mongodb3#31]
`recipes/mongos.rb` has these lines:

```
# Create the log directory
directory File.dirname(node['mongodb3']['config']['mongos']['systemLog']['path']).to_s do
  owner node['mongodb3']['user']
  action :create
  recursive true
end
```

`recipes/default.rb` does not and if the directory does not exist, the service won't start.

**Comment by sunggun-yu** [comment]
Hi,
mongo package creates default log directory. so, I wasn't assuming using different directory.
please have some wrapper for directory creation. I'll consider adding functionality as well.

Thank you.

**Comment by tuky** [comment]
Thank you. For now, I fell back to the default location. I think, the logs can become very large and in other cases it might be better for the logs to reside on a different location than the db data in terms of performance.

**Comment by sunggun-yu** [comment]
@tuky 
Thank you. I would recommend to have some mount point for log directory. meanwhile,  providing functionality is on the way.

**Comment by rveznaver** [comment]
This feature breaks syslog log configuration since you cannot use `['systemLog']['path']` with `['systemLog']['destination'] = 'syslog'`.
