### ISSUE TITLE
ssl values should be configurable

### ISSUE THREAD

**Issue by mkianpour** [sunggun-yu/chef-mongodb3#34]
Can you please add support for configuration of the following attributes:
sslTrustedMMSServerCertificate, sslRequireValidMMSServerCertificates

Thanks,
Mehdi

**Comment by nicka** [comment]
@sunggun-yu Any news on this?

**Comment by sunggun-yu** [comment]
@mkianpour @nicka 
I'm so sorry for late checking this issue guys. unfortunately, I have no change to look into it. 
I'll take a look! sorry again!

**Comment by sunggun-yu** [comment]
@mkianpour , @nicka 
I've released v5.2.0 that is supporting this request. 
Thank you.

**Comment by nicka** [comment]
Awesome work!!!

**Comment by sunggun-yu** [comment]
@nicka 
Thank you!

**Comment by mkianpour** [comment]
Thank you very much! really helpful

BR,
Mehdi
