### ISSUE TITLE
how to boot up mongodb with option?

### ISSUE THREAD

**Issue by chuangtim** [sunggun-yu/chef-mongodb3#37]
what is a good way to boot up mongodb with option? default boot up way as following:

``` ruby
/usr/bin/mongod --config /etc/mongod.conf
```

any idea? thx

**Comment by sunggun-yu** [comment]
@chuangtim I think that is best way to startup mongodb. 
will close out this issue since it is not related to this cookbook.
Thanks

**Comment by chuangtim** [comment]
@sunggun-yu  I see,but what I mean is using mongodb options, for example:

``` ruby
/usr/bin/mongod --slave --config /etc/mongod.conf
```

this cookbook can`t startup with --slave
