### ISSUE TITLE
Mongodb configuration file generation

### ISSUE THREAD

**Issue by vachanda** [sunggun-yu/chef-mongodb3#9]
The helper for the mongodb configuration template fails to delete the null values and update the hash, as the object being received by it is of type ImmuatableMash.

**Comment by vkhatri** [comment]
@vachanda could you please share `Chef` client/server version and `OS` details? would be great to have stack trace and chef client run error message.

**Comment by vachanda** [comment]
Hey sorry, I forgot to mention this in my earlier comment. The Chef version is 11.10 and OS is Ubuntu 14.04 LTS. The stack trace is not available as it is been removed when the ec2 machine was terminated. It basically says "Cannot set the value of a node.default['key'] = value, use set method to do it". This is because in the helper you are trying to remove the keys and store it in the same object. This is not possible since the object is immutable.

**Comment by sunggun-yu** [comment]
@vachanda Thank you for heads up. I'll take a look.

**Comment by dblock** [comment]
Close via https://github.com/sunggun-yu/chef-mongodb3/pull/22.

**Comment by sunggun-yu** [comment]
Thank you!
